minimum_pre_commit_version: "4.4.0"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-check
        args: [--fix]

      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: Run unit tests
        entry: python -m pytest --cov=app --cov-report=term-missing --cov-fail-under=90
        language: unsupported
        pass_filenames: false
        always_run: true
        stages: [pre-commit]